#sudo: true
#language: python
#python:
#  - '3.5'
#  - '3.6'
#env:
#  global:
#    - DB=postgres
#  matrix:
#    - DJANGO=">=1.11,<2.0"
#    - DJANGO=">=2.0,<2.1"
#addons:
#  postgresql: '9.5'
#install:
#  - pip install -q coverage coveralls flake8 Django$DJANGO django-nose>=1.4
#before_script:
#  - psql -c 'CREATE DATABASE querybuilder;' -U postgres
#script:
#  - flake8 ./querybuilder
#  - coverage run setup.py test
#  - coverage report --fail-under=90
#after_success:
#  coveralls
#
#
#
#

language: python
#cache: pip

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

sudo: false

env:
  global:
    - DB=postgres
  - DJANGO=1.10
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=master

addons:
  postgresql: '9.5'

matrix:
  include:
    - { python: 3.6, env: TOXENV=flake8 }

#    fast_finish: true
#    include:
#      - { python: "3.6", env: DJANGO=master }
#      - { python: "3.6", env: DJANGO=1.11 }
#      - { python: "3.6", env: DJANGO=2.0 }
#      - { python: "2.7", env: TOXENV=lint }
#      - { python: "2.7", env: TOXENV=docs }

#      - python: "3.6"
#        env: TOXENV=dist
#        script:
#          - python setup.py bdist_wheel
#          - tox --installpkg ./dist/djangorestframework-*.whl
#          - tox  # test sdist
#
#      - python: "3.6"
#        env: TOXENV=readme
#        addons:
#          apt_packages: pandoc

#    exclude:
#      - { python: "2.7", env: DJANGO=master }
#      - { python: "2.7", env: DJANGO=2.0 }
#      - { python: "3.4", env: DJANGO=master }

#    allow_failures:
#      - env: DJANGO=master

install:
    - pip install tox-travis

before_script:
  - psql -c 'CREATE DATABASE querybuilder;' -U postgres

script:
    - tox

#after_success:
#    - pip install codecov
#    - codecov -e TOXENV,DJANGO

notifications:
    email: false
